export enum KnownCharId {
    Wolf = 'Wolf',
    Crow = 'Crow',
    Cat = 'Cat',
    Mouse = 'Mouse',
    Dog = 'Dog',
    Granny = 'Granny',
    Lion = 'Lion',
    Elephant = 'Elephant',
    Rooster = 'Rooster',
    Owl = 'Owl',
    Chicken = 'Chicken',
    Bear = 'Bear',
    Fox = 'Fox',
    Fish = 'Fish',
    Girl = 'Girl',
    Zombie = 'Zombie',
    Grandfather = 'Grandfather',
    Alice = 'Alice',
    HarryPotter = 'HarryPotter',
    Rat = 'Rat',
    Cow = 'Cow',
    Crocodile = 'Crocodile',
    Tiger = 'Tiger',
    Dino = 'Dino',
    Horse = 'Horse',
    Frog = 'Frog',
}
